export const styles = {
  container: {
    position: 'relative',
    width: '100%',
  } as React.CSSProperties,
  overlay: {
    position: 'absolute' as const,
    inset: 0,
    overflow: 'hidden',
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
    padding: 12,
    zIndex: 10,
    fontSize: 14,
    lineHeight: 1.5,
    pointerEvents: 'none' as const,
  },
  mention: {
    color: '#1d4ed8',
    textDecoration: 'underline',
    fontWeight: 400,
    pointerEvents: 'auto' as const,
  } as React.CSSProperties,
  text: {
    color: 'transparent',
    fontSize: 14,
    pointerEvents: 'none' as const,
  } as React.CSSProperties,
  dropdown: {
    position: 'absolute' as const,
    zIndex: 50,
    width: 256,
    maxHeight: 256,
    overflow: 'hidden',
    boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05)',
    border: '1px solid #e5e7eb',
    backgroundColor: '#ffffff',
  } as React.CSSProperties,
  dropdownHeader: {
    fontSize: 12,
    fontWeight: 500,
    color: '#6b7280',
    marginBottom: 8,
    padding: '0 8px',
  } as React.CSSProperties,
  list: {
    maxHeight: 192,
    overflowY: 'auto' as const,
  } as React.CSSProperties,
  listItem: (active: boolean) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: 8,
    cursor: 'pointer',
    backgroundColor: active ? '#eff6ff' : 'transparent',
    border: active ? '1px solid #bfdbfe' : '1px solid transparent',
  }) as (active: boolean) => React.CSSProperties,
  footer: {
    fontSize: 12,
    color: '#9ca3af',
    marginTop: 8,
    padding: '8px',
    borderTop: '1px solid #e5e7eb',
  } as React.CSSProperties,
};
