export const SOC2_PAGES: Record<number, string> = {
  7: `SOC 2 Security Report 2025 - Page 7\n\nSECURITY FRAMEWORK OVERVIEW\n\nThe organization has implemented a comprehensive security framework based on industry best practices and regulatory requirements. This framework encompasses multiple layers of security controls designed to protect sensitive data and ensure business continuity.\n\nKey components of the security framework include:\n• Physical security controls\n• Network security architecture  \n• Data classification and handling procedures\n• Identity and access management\n• Incident response procedures\n\nThe security framework is reviewed annually and updated as needed to address emerging threats and changing business requirements.`,
  8: `SOC 2 Security Report 2025 - Page 8\n\nDATA ENCRYPTION STANDARDS\n\nThe organization maintains robust data protection through comprehensive encryption protocols. All sensitive data is protected using industry-standard encryption methodologies.\n\nData at Rest Protection:\nVendor has implemented encryption for data at rest using AES-256. All database systems, file storage, and backup media utilize this encryption standard to ensure data confidentiality. The encryption keys are managed through a centralized key management system with appropriate access controls and rotation schedules.\n\nAudit logs indicate compliance with policy as of March 2025. Regular monitoring and testing procedures verify the effectiveness of encryption implementations across all systems.\n\nData in Transit Protection:\nAll data transmissions utilize TLS 1.3 or higher encryption protocols. Network communications between systems and external connections are secured using approved cryptographic standards.`,
  9: `SOC 2 Security Report 2025 - Page 9\n\nACCESS CONTROL IMPLEMENTATION\n\nThe organization has implemented comprehensive access control measures to ensure appropriate user permissions and prevent unauthorized access to sensitive systems and data.\n\nRole-Based Access Control (RBAC):\nUser access rights are assigned based on job responsibilities and principle of least privilege. Regular access reviews are conducted quarterly to ensure permissions remain appropriate.\n\nMulti-Factor Authentication:\nAll users accessing critical systems must utilize multi-factor authentication, including hardware tokens or mobile app-based authentication methods.`,
};

export const IPSRA_PAGES: Record<number, string> = {
  12: `DATA CLASSIFICATION STANDARDS\n\nThe organization has implemented comprehensive data classification standards to ensure appropriate handling, storage, and protection of information based on sensitivity and criticality.\n\nData classification categories include:\n• Public: Information that can be shared freely without restriction\n• Internal: Information intended for use within the organization\n• Confidential: Sensitive business information requiring protection\n• Restricted: Highly sensitive information with strict access controls\n\nEach classification level has defined handling requirements, access controls, and retention policies that are enforced through technical and administrative controls.`,
};
